function eta_e = F_eta(x)
    % Waste Heat Recovery Efficiency Equation
    T_hw_in = x(1);     % Hot water inlet temperature [°C]
    T_cw_in = x(2);     % Cold water inlet temperature [°C]
    T_chw_in = x(3);    % Chilled water inlet temperature [°C]
    m_hw = x(4);        % Hot water mass flow rate [kg/s]
    m_cw_bed = x(5);    % Cooling water mass flow rate (bed) [kg/s]
    m_chw = x(6);       % Chilled water mass flow rate [kg/s]
    m_cw_cond = x(7);   % Cooling water mass flow rate (condenser) [kg/s]
    U_bed_A_bed = x(8); % Heat transfer coefficient × area (bed) [W/K]
    U_evap_A_evap = x(9); % Heat transfer coefficient × area (evaporator) [W/K]
    U_cond_A_cond = x(10); % Heat transfer coefficient × area (condenser) [W/K]

    % Waste heat recovery efficiency equation
    eta_e = -0.2347 ...
        - 0.00037 * T_hw_in ...
        - 0.0019 * T_cw_in ...
        + 0.0026 * T_chw_in ...
        + 0.0277 * m_hw ...
        + 0.0034 * m_cw_bed ...
        + 0.0150 * m_chw ...
        + 0.0019 * m_cw_cond ...
        + 2.0286e-6 * U_bed_A_bed ...
        + 1.0279e-6 * U_evap_A_evap ...
        + 6.8084e-8 * U_cond_A_cond;
end
